# This is a basic workflow to help you get started with Actions

name: Unofficial Docs


# Controls when the workflow will run
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install pdoc3
        run: pip install pdoc3
      - name: Install ourselves
        run: pip install git+https://github.com/Textualize/textual.git#css

      # Runs a set of commands using the runners shell
      - name: Make the docs
        run: pdoc3 --skip-errors -o undocs/docs --html -c "lunr_search={'fuzziness':1,'index_docstrings':True}" textual
        
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: undocs # The folder the action should deploy.
